In [2]:
import numpy as np
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
L=a.tolist()
L

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [9]:
a =np.array([9,0,0,0,1,0,0,5])
L=a.tolist()
L

[9, 0, 0, 0, 1, 0, 0, 5]

In [21]:
L=[]
x=a.shape
print(x)
y=x[0]
print(y)

for i in range(y):
    L.append(a[i])
L

(8,)
8


[9, 0, 0, 0, 1, 0, 0, 5]

In [23]:
a = np.array([[0,1,2],[3,4,5],[6,7,8]])
L=[]
x=a.shape
print(x)
y=x[0]
print(y)
for i in range(y):
    L.append(a[i,:])
L

(3, 3)
3


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [24]:
#question 2


In [32]:
a = np.array([[0,1,2],[3,4,5],[6,7,9]])
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 9]])

In [33]:
sum=0
x=a.shape
raw1=x[0]
col1=x[1]
for i in range (raw1):
    sum+= a[i,i]
sum

13

In [34]:
y=np.trace(a)
y

13

In [50]:
y1=np.trace(a,1,0)
print(y1)
y2=np.trace(a,2,0)
print(y2)
y3=np.trace(a,-1,0)
print(y3)
y4=np.trace(a,-2,0)
print(y4)

6
2
10
6


In [52]:
a = np.array([[0,1,2],[3,4,5],[6,7,9],[10,11,12]])
a


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  9],
       [10, 11, 12]])

In [54]:
y=np.trace(a)
print(y)
y1=np.trace(a,1,0)
print(y1)
y2=np.trace(a,2,0)
print(y2)
y3=np.trace(a,-1,0)
print(y3)
y4=np.trace(a,-2,0)
print(y4)
y5=np.trace(a,-3,0)
print(y5)

13
6
2
22
17
10


In [56]:
#question 3

In [60]:
b =np.array([[1,2],[3,5]]) 

print(b[b>2])

[3 5]


In [61]:
#question4

In [6]:
x=np.array([[1,2],[3,4],[1,2]])
y=np.array([[5,6],[7,8],[1,2]])
A=x+y
print(A)

b=np.add(x, y)
b

[[ 6  8]
 [10 12]
 [ 2  4]]


array([[ 6,  8],
       [10, 12],
       [ 2,  4]])

In [73]:
array=np.random.randint(2, 10, size=(2,4))
print(array)

[[9 4 9 6]
 [2 3 5 4]]


In [34]:

f=x.shape
print(f)
y=f[0]
z=f[1]
c=np.random.randint(2, 10, size=(y,z))


print(c)


(4, 3)
[[5 4 8]
 [2 9 9]
 [2 7 9]
 [9 7 4]]


In [46]:
#question 5
x = np.random.randint(5, 30, size=(4,3))
x

array([[11,  8, 10],
       [ 7,  8,  5],
       [ 9, 10,  5],
       [ 5, 15, 28]])

In [47]:
f=x.shape
print(f)
n=f[0]
for i in range(n):
    y = np.mean(x[i])
    print("the mean of row",i," =", y)

(4, 3)
the mean of row 0  = 9.666666666666666
the mean of row 1  = 6.666666666666667
the mean of row 2  = 8.0
the mean of row 3  = 16.0
